# Generated by Django 2.2.3 on 2019-08-01 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quizzers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('password', models.CharField(max_length=40, verbose_name='Password')),
                ('mobile', models.CharField(max_length=10, verbose_name='Mobile Number')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active User')),
                ('is_contributer', models.BooleanField(default=False, verbose_name='Contributer')),
                ('is_stud', models.BooleanField(default=True, verbose_name='Stud')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
