# Generated by Django 4.0.4 on 2022-04-23 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190804_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzers',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
