# Generated by Django 2.2.4 on 2019-08-23 04:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='Title')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quiztitle', models.CharField(default=None, max_length=30, verbose_name='Title')),
                ('level', models.CharField(choices=[('SI', 'simple'), ('MED', 'medium'), ('HA', 'hard')], max_length=3)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.Category')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('users_submitted', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questiontitle', models.CharField(max_length=400, verbose_name='Title')),
                ('op1', models.CharField(max_length=400, verbose_name='Option 1')),
                ('op2', models.CharField(max_length=400, verbose_name='Option 2')),
                ('op3', models.CharField(max_length=400, verbose_name='Option 3')),
                ('op4', models.CharField(max_length=400, verbose_name='Option 4')),
                ('answer', models.CharField(max_length=400, verbose_name='Answer')),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.Quiz')),
            ],
        ),
    ]
