# Generated by Django 2.2.4 on 2019-08-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='score',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='score',
            name='total_questions',
            field=models.IntegerField(),
        ),
    ]
