# Generated by Django 2.2.4 on 2019-08-23 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_auto_20190823_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='studs',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
