# Generated by Django 2.2.4 on 2019-08-23 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_auto_20190823_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='score',
            name='studs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
